// <auto-generated />
namespace Democracy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20102016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20102016));
        
        string IMigrationMetadata.Id
        {
            get { return "201610201945204_20102016"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
